name: GitHub Actions Demo

on: [push]
jobs:
  My-CI-CD-Job:
    runs-on: ubuntu-latest
    steps:
      - name: hello wonderful
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
